# 数组创建

In [1]:
import numpy as np
arr1 = np.array([1,2,3,4])# 采用numpy.array（object）创建一维数组
print("创建的数组为:",arr1)

创建的数组为: [1 2 3 4]


In [8]:
print("arr1数组元素类型:",arr1.dtype)
print("arr1数组维度:",arr1.shape)
print("arr1数组元素个数:",arr1.size)
print("arr1数组内每个元素大小:",arr1.itemsize)

arr1数组元素类型: int32
arr1数组维度: (4,)
arr1数组元素个数: 4
arr1数组内每个元素大小: 4


In [6]:
arr2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [8]:
print("arr2数组维度:",arr2.shape)
arr2.shape = 4,3 #可以更改arr2的维度
print(arr2)

arr2数组维度: (4, 3)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [9]:
arr3 = np.arange(0,1,0.1) # 采用numpy.arange（start=0,stop,step=1,dtype=None）,返回值为[start,stop)的所有整数的数组
print(arr3)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [10]:
arr3_1 = np.arange(5) #相当于np.arrange(0,5,1)
print(arr3_1)

[0 1 2 3 4]


In [14]:
arr4 = np.linspace(0,100,11,endpoint=False,retstep=True) #采用numpy.linspace（start,stop,num=50,endpoint=True,retstep=False,dtype=None）构造等差数列
print(arr4) #输出会显示间距

(array([ 0.        ,  9.09090909, 18.18181818, 27.27272727, 36.36363636,
       45.45454545, 54.54545455, 63.63636364, 72.72727273, 81.81818182,
       90.90909091]), 9.090909090909092)


In [22]:
arr5 = np.logspace(0,2,20) #numpy.logspace（start,stop,num=50,endpoint=True,base=10.0,dtype=None）构造等比数列,X=10^(start到stop)
print(arr5)

[  1.           1.27427499   1.62377674   2.06913808   2.6366509
   3.35981829   4.2813324    5.45559478   6.95192796   8.8586679
  11.28837892  14.38449888  18.32980711  23.35721469  29.76351442
  37.92690191  48.32930239  61.58482111  78.47599704 100.        ]


In [15]:
arr6=np.zeros((2,3)) #创建指定维度数组，并以0补充,参数为元组
print(arr6)

[[0. 0. 0.]
 [0. 0. 0.]]


In [42]:
arr9 = np.ones((5,3)) #创建元素全为1的数组，参数为元组
print(arr9)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [18]:
arr6_1 = np.zeros(3)
print(arr6_1)

[0. 0. 0.]


In [14]:
arr9_1 = np.ones(5)
print(arr9_1)

[1. 1. 1. 1. 1.]


In [17]:
arr7=np.eye(3) #创建主对角线为1，其他为0的n*n的数组
print(arr7)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [38]:
arr8=np.diag([1,2,3,4]) #创建除对角线其余为0的n*n数组
print(arr8)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


# NumPy类型

In [20]:
print(np.float64(42))

42.0


In [41]:
print(np.int8(42.0))

42


In [19]:
df = np.dtype([("name",np.str_,40),("numitems",np.int64),("price",np.float64)]) #使用numpy.dtype函数得到自定义数组数据类型
print(df)
print(df["name"]) #输出为 顺序+字符编码或类型+大小

[('name', '<U40'), ('numitems', '<i8'), ('price', '<f8')]
<U40


In [30]:
item = np.array([("tomatos",42,4.14),("cabbages",13,1.72)],dtype=df) #使用df自定义数据数据和类型，否则默认数组类型为浮点型
print(item)
print(item[0])
print(item[0][0])
print(item[0]["name"])

[('tomatos', 42, 4.14) ('cabbages', 13, 1.72)]
('tomatos', 42, 4.14)
tomatos
tomatos


# NumPy获取随机数

In [21]:
arr10 = np.random.random(10) #调用numpy.random模块中的random(x)函数生成10个位于[0.0,1.0)的随机数组,x为整数或元组
print(arr10)

[0.60927457 0.0755398  0.05441362 0.07496466 0.59392243 0.10532571
 0.4942526  0.83914151 0.16948686 0.87223135]


In [51]:
arr10_1 = np.random.random((2,2)) #返回2行2列位于[0.0,1.0)的随机二维数组
print(arr10_1)

[[0.00687427 0.76199481]
 [0.73478702 0.06661069]]


In [40]:
arr10_2 = np.random.rand(10) #调用numpy.random模块中的rand(d0,d1....dn)函数生成10个位于[0,1)的随机数,传入数字的个数为维度
print(arr10_2)

[0.70169219 0.2778348  0.82472824 0.97473655 0.17426052 0.38284404
 0.3476404  0.11479885 0.46159736 0.95211826]


In [42]:
arr10_3 = np.random.rand(2,5) #返回2行5列位于[0,1)的随机二维数组
print(arr10_3)

[[0.4917506  0.33252507 0.51218419 0.71531702 0.91183191]
 [0.92231678 0.72239269 0.23255209 0.30525234 0.07008274]]


In [43]:
arr10_4 = np.random.randn(3) #调用np.random模块的randn函数(d0,d1....dn)返回10个符合正态分布的随机数,参数个数表示维度
print(arr10_4)

[ 0.88421886 -1.78317583  0.88701036]


In [44]:
arr10_5 = np.random.randn(2,3) #返回符合正态分布的2行3列二维随机数组
print(arr10_5)

[[ 0.83414622 -1.58018707  0.10735155]
 [-1.27807074  1.61662767 -1.61046125]]


In [45]:
arr10_6=np.random.randint(2,10,5) #调用np.random模块的randint（low,high=None,size=None）函数返回10个位于[2,10)的整数,size可为整数或元组,为None仅返回一个整数
print(arr10_6)

[9 9 2 2 5]


In [47]:
arr10_7=np.random.randint(2,10,(2,5)) #返回位于[2,10)的2行5列的二维整数数组
print(arr10_7)

[[6 2 7 5 2]
 [9 5 8 2 6]]


In [48]:
arr10_8=np.random.randint(2,size=(2,5)) #返回位于[0,2)的2行5列的二维整数数组
print(arr10_8)

[[0 1 0 0 1]
 [1 0 0 0 0]]


In [49]:
arr10_9 = np.random.normal(0,0.1,10) # np.random.normal(loc,scale,size),生成用于正态分布的随机数，loc为期望，scale为标准差，size为数组维数
print(arr10_9)

[ 0.03181897 -0.18416345  0.051958    0.01697182  0.0877833  -0.01514626
  0.11935034  0.11849879  0.05728848 -0.10995221]


In [50]:
arr10_10 = np.random.normal(0,0.1,(2,5)) #返回2行5列均值为0，标准差为0.1的正态分布随机二维数组
print(arr10_10)

[[ 0.00527994  0.20829987  0.09871357  0.03495009  0.04005295]
 [-0.01343154 -0.06297035 -0.12099749 -0.10342378 -0.03218473]]


# 数组索引和切片

In [62]:
n1 = np.array([1,2,3])
print(n1[0])
print(n1[-1])

1
3


In [22]:
n2 = np.array([[1,2,3],[4,5,6]])
print(n2[0][1])
print(n2[0][-1])
print(n2[-1,-1])

2
3
6


切片 start:stop:step , 范围为[start，stop)

In [23]:
n3=np.array([1,2,3,4])
print(n3[0:3:1])
print(n3[0:4:2])
print(n3[0:5]) #step默认为1,相当于[0:4:1]
print(n3[:3]) #start默认为0,step默认为1，相当于[0:3:1]
print(n3[0:]) #stop默认为最后一个元素的下一个下标,相当于[0:4:1]
print(n3[:]) #相当于[0:4]
print(n3[::]) #相当于[0:4:1]
print(n3[::-1]) #step为-1，默认逆序输出
print(n3[:-3:-1]) #step=-1，此时start默认-1，倒数第一个到倒数第三个，不包括倒数第三个
print(n3[-3::-1]) #倒数第三个到倒数最后一个
print(n3[-3:-4:-1]) #倒数第三个到倒数第四个，不包括倒数第四个

[1 2 3]
[1 3]
[1 2 3 4]
[1 2 3]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[4 3 2 1]
[4 3]
[2 1]
[2]


In [24]:
n4=np.array([[1,2,3],[4,5,6]])
print(n4)
print()
print(n4[0:,1:]) # 取第一行第二行，和第二列第三列交叉点的元素
print()
print(n4[0:,1]) # 取第一行第二行，和第二列交叉点的元素
print()
print(n4[((0,1,0),(0,1,2))]) #取n4坐标为[0,0],[1,1],[0,2]的元素

[[1 2 3]
 [4 5 6]]

[[2 3]
 [5 6]]

[2 5]

[1 5 3]


# 数组变换形态

In [120]:
n5=np.arange(10)
print(n5)
n5 = n5.reshape(2,5) #reahpe函数改变数组的维数，这里由一维数组变为2行5列的二维数组
print(n5)
print("转换为2行5列:\n",n5.ravel()) #ravel函数横向展开数组，化成一维
#flatten函数可以横向或纵向展开数组，纵向展开数组参数为'F'.
print("纵向展开后:\n",n5.flatten('F'))
print("横向展开后:\n",n5.flatten())
#使用数组的T属性转置
print("T属性转置后:\n",n5.T)
#使用transpose函数转置
print("transpose函数转置后:\n",n5.transpose())

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
转换为2行5列:
 [0 1 2 3 4 5 6 7 8 9]
纵向展开后:
 [0 5 1 6 2 7 3 8 4 9]
横向展开后:
 [0 1 2 3 4 5 6 7 8 9]
T属性转置后:
 [[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
transpose函数转置后:
 [[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [25]:
n6 = np.arange(12).reshape(3,4)
print(n6)
n7 = n6*3 #n6中的每个元素都*3
print(n7)
print("横向组合为:\n",np.hstack((n6,n7))) #np.hstack((arr1,arr2...))函数横向组合数组
print("纵向组合为:\n",np.vstack((n6,n7,n6))) #np.vstack((arr1,arr2...))函数纵向组合数组
#使用np.concatenate((arr1,arr2...),axis=1或者0)函数组合数组
print("横向组合为:\n",np.concatenate((n6,n7),1)) #横向组合数组
print("纵向组合为:\n",np.concatenate((n6,n7,n6),0)) #纵向组合数组

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]
横向组合为:
 [[ 0  1  2  3  0  3  6  9]
 [ 4  5  6  7 12 15 18 21]
 [ 8  9 10 11 24 27 30 33]]
纵向组合为:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
横向组合为:
 [[ 0  1  2  3  0  3  6  9]
 [ 4  5  6  7 12 15 18 21]
 [ 8  9 10 11 24 27 30 33]]
纵向组合为:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [110]:
n8 = np.arange(16).reshape(4,4)
print(n8)
#采用np.hsplit(arr,num)实现横向分割，num为分割的部份数，分割的部分元素数相同
print("横向分割后:\n",np.hsplit(n8,2)) 
#采用np.vsplit(arr,num)实现纵向分割，num为分割的部份数，分割的部分元素数相同
print("纵向分割后:\n",np.vsplit(n8,2)) 
#使用np.split(arr,num,axis=0或1)实现分割
print("横向分割后:\n",np.split(n8,4,1)) 
print("纵向分割后:\n",np.split(n8,4,0))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
横向分割后:
 [array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]
纵向分割后:
 [array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
横向分割后:
 [array([[ 0],
       [ 4],
       [ 8],
       [12]]), array([[ 1],
       [ 5],
       [ 9],
       [13]]), array([[ 2],
       [ 6],
       [10],
       [14]]), array([[ 3],
       [ 7],
       [11],
       [15]])]
纵向分割后:
 [array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]


# 数组删除和修改

In [26]:
n9=np.arange(6).reshape(3,2)
print(n9)
#采用np.delete(arr,size,axis=0或1)删除某几行或几列，axis=1删除列，axis=0删除行
print("删除第一行:\n",np.delete(n9,0,0))
print("删除第一列:\n",np.delete(n9,0,1))
print("删除第一行和第二行:\n",np.delete(n9,(0,1),0))
n9[0]=[10,20]
print("修改第一行数据:\n",n9)
n9[0][1]=100 #或者n9[0,1]
print("修改第一行第二列的值:\n",n9)

[[0 1]
 [2 3]
 [4 5]]
删除第一行:
 [[2 3]
 [4 5]]
删除第一列:
 [[1]
 [3]
 [5]]
删除第一行和第二行:
 [[4 5]]
修改第一行数据:
 [[10 20]
 [ 2  3]
 [ 4  5]]
修改第一行第二列的值:
 [[ 10 100]
 [  2   3]
 [  4   5]]


## 行操作0 列操作1

# 数组查询

In [124]:
n10=np.arange(10)
print(n10)
#调用np.where(condition,x,y)函数进行查询，如果元素满足条件condition则输出为x,否则y；若果不指定参数x和y，则输出满足函数条件数组元素的下标
print(np.where(n10>5,1,0)) 
print(n10[np.where(n10>5)])

[0 1 2 3 4 5 6 7 8 9]
[0 0 0 0 0 0 1 1 1 1]
[6 7 8 9]


# NumPy矩阵创建

矩阵是ndarray的子类。  
矩阵和数组是两种不同的类型。  
NumPy提供了两个基本的对象：ndarray和ufunc对象，其他对象都是在他们的基础上构建的。  
矩阵是继承NumPy n维数组对象的二维数组对象

In [3]:
a = np.mat("1 2;3 4") #采用no.mat(data,copy=False)函数创建矩阵,使用分号隔开数据
b = np.mat([[1,2],[3,4]])
print(a)
print(type(a))
print(b)
print(type(b))
c = np.array([[1,2],[3,4]])
print(c)
print(type(c))

[[1 2]
 [3 4]]
<class 'numpy.matrix'>
[[1 2]
 [3 4]]
<class 'numpy.matrix'>
[[1 2]
 [3 4]]
<class 'numpy.ndarray'>


In [12]:
d = np.mat(np.zeros((3,3)))
print(d)
e = np.mat(np.ones((2,4)))
print(e)
f = np.mat(np.random.rand(3,3))#生成3*3的位于[0.0,1.0)的随机矩阵
print(f)
g = np.mat(np.random.randint(1,8,(3,5)))#生成3*5的位于[1,8)的随机整数矩阵
print(g)
h = np.mat(np.eye(2,dtype=int))#生成2*2的单位矩阵
print(h)
i = np.mat(np.diag([1,2,3,4])) #生成对角线为1，2，3，4的对角矩阵
print(i)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0.31341443 0.86931598 0.65093993]
 [0.50399789 0.1931321  0.8713872 ]
 [0.18064965 0.13675115 0.05571409]]
[[1 5 7 7 1]
 [1 7 7 3 3]
 [4 6 3 1 4]]
[[1 0]
 [0 1]]
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [14]:
j1 = np.eye(3)
j2 = 3*j1
j = np.bmat("j1 j2;j2 j1") #采用np.bmat函数创建分块矩阵
print(j)

[[1. 0. 0. 3. 0. 0.]
 [0. 1. 0. 0. 3. 0.]
 [0. 0. 1. 0. 0. 3.]
 [3. 0. 0. 1. 0. 0.]
 [0. 3. 0. 0. 1. 0.]
 [0. 0. 3. 0. 0. 1.]]


矩阵的加减除和对应元素乘，都具有广播机制，即自动补齐至对应元素可以运算的程度

In [3]:
k = np.mat([[1,2],[3,4],[5,6]])
m = np.mat("1 2")
print("\nm+k:")#对应元素相加
print(k,"\n    +  \n",m,"\n    =  \n",k+m)
print("\nk-m:")#对应元素相减
print(k,"\n    -  \n",m,"\n    =  \n",k-m)
print("\nm-k:")
print(m,"\n    -  \n",k,"\n    =  \n",m-k)
print("m/k:")#对应元素相除
print(m/k)
print("k/m:")
print(k/m)
print("矩阵元素相乘")
print(np.multiply(k,m))#对应元素相乘


m+k:
[[1 2]
 [3 4]
 [5 6]] 
    +  
 [[1 2]] 
    =  
 [[2 4]
 [4 6]
 [6 8]]

k-m:
[[1 2]
 [3 4]
 [5 6]] 
    -  
 [[1 2]] 
    =  
 [[0 0]
 [2 2]
 [4 4]]

m-k:
[[1 2]] 
    -  
 [[1 2]
 [3 4]
 [5 6]] 
    =  
 [[ 0  0]
 [-2 -2]
 [-4 -4]]
m/k:
[[1.         1.        ]
 [0.33333333 0.5       ]
 [0.2        0.33333333]]
k/m:
[[1. 1.]
 [3. 2.]
 [5. 3.]]
矩阵元素相乘
[[ 1  4]
 [ 3  8]
 [ 5 12]]


In [5]:
print(k)
n = np.mat("1;2;3")
print(n)
print(n+k)

[[1 2]
 [3 4]
 [5 6]]
[[1]
 [2]
 [3]]
[[2 3]
 [5 6]
 [8 9]]


In [30]:
a1 = np.mat("1 2;3 4;5 6")
a2 = np.mat('1 2;3 4')
a3=np.mat('1;2')
print(a1*a2)
print(a1*a3)

[[ 7 10]
 [15 22]
 [23 34]]
[[ 5]
 [11]
 [17]]


In [31]:
a4 = np.mat("1 2 3;4 5 6;7 8 9")
print(a4)
print(a4.T) #打印转置矩阵
print(a4.I) #打印逆矩阵
print(a4.H) #打印共轭转置矩阵
print(a4.A) #返回二维数组的视图(相当于矩阵的引用)
a5 = a4.A
a5[1,2]=10
print(a4)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [ 4  5 10]
 [ 7  8  9]]


数组的加减乘除和比较，都具有广播机制，即自动补齐至对应元素可以运算的程度

In [16]:
a5 = np.array([[0,0,0],[1,1,1],[2,2,2],[3,3,3]])
a6 = np.array([1,2,3])
print(a5+a6)
print()
print(a5-a6)
print()
print(a6-a5)
print()
print(a5*a6)
print()
print(a5/a6)
print()
print(a5**a6)
print()
print(a6**a5)
print()
print(a6<a5)
print()
print(np.all(a5==a6)) #np.all函数表示逻辑“and”，运算结果返回布尔值。
print(np.any(a5==a6)) #np.any函数表示逻辑“or”，运算结果返回布尔值

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]

[[-1 -2 -3]
 [ 0 -1 -2]
 [ 1  0 -1]
 [ 2  1  0]]

[[ 1  2  3]
 [ 0  1  2]
 [-1  0  1]
 [-2 -1  0]]

[[0 0 0]
 [1 2 3]
 [2 4 6]
 [3 6 9]]

[[0.         0.         0.        ]
 [1.         0.5        0.33333333]
 [2.         1.         0.66666667]
 [3.         1.5        1.        ]]

[[ 0  0  0]
 [ 1  1  1]
 [ 2  4  8]
 [ 3  9 27]]

[[ 1  1  1]
 [ 1  2  3]
 [ 1  4  9]
 [ 1  8 27]]

[[False False False]
 [False False False]
 [ True False False]
 [ True  True False]]

False
True


# 读写文件

In [71]:
a20 = np.arange(12).reshape(3,4)
a21 = np.arange(12,24).reshape(3,4)
np.save("./ArrayMemory/a20Memory",a20) # 调用np.save(file, arr, allow_pickle=True, fix_imports=True)把数组arr保存至名称为“file”的文件中，其文件的扩展名.npy是系统自动添加的。
np.savez("./ArrayMemory/a20a21Memory",a20,a21) #调用np.savez(file,arr1,arr2...)函数，将多个数组保存到一个文件中，其文件的扩展名为.npz。
print(np.load("./ArrayMemory/a20Memory.npy")) #调用np.load(file)从文件中读取数组
loadData = np.load("./ArrayMemory/a20a21Memory.npz")
print(loadData['arr_0']) #这个[]里面的东西如果你在savaz时没有指定Key则只能以这种形式写，arr_0,arr_1,arr_...
print(loadData['arr_1'])
np.savez("./ArrayMemory/Memory",a=a20,b=a21)
loadData = np.load("./ArrayMemory/Memory.npz")
print(loadData['a'])  #这里由于我们在savez时指定了key，所以我们可以用自己的指定的key值访问不同的数组
print(loadData["b"])
np.savetxt("./ArrayMemory/a.txt",a20,fmt='%d',delimiter=',') #调用np.savetxt(file,arr,fmt,delimiter)函数将arr以fmt的形式，delimiter为分隔符保存到file中
print(np.loadtxt("./ArrayMemory/a.txt",delimiter=','))#调用np.loadtxt(file,delimiter)函数将arr以delimiter为分隔符从file中读出
print(np.genfromtxt("./ArrayMemory/a.txt",delimiter=',')) #调用np.genfromtxt(file,delimiter)函数将arr以delimiter为分隔符从file中读出，面向的是结构化数组和缺失数据

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


# 使用数组进行简单数据分析

In [11]:
a7 = np.random.randint(1,20,10)
print(a7)
print(a7.argsort()) #返回排序值的下标，不会改变原数组
print(a7)
a7.sort() #调用数组的sort()函数对函数进行排序
print(a7)


[19 14 17  4 17 18  1  4 16 12]
[6 3 7 9 1 8 2 4 5 0]
[19 14 17  4 17 18  1  4 16 12]
[ 1  4  4 12 14 16 17 17 18 19]


In [8]:
a8 = np.random.randint(1,20,12).reshape(3,4)
print(a8)
a8.sort(axis=1) #横向排序
print(a8)
a8.sort(0)  #纵向排序
print(a8) 

[[14 19  6 10]
 [15 15 19  2]
 [ 3 10  7 15]]
[[ 6 10 14 19]
 [ 2 15 15 19]
 [ 3  7 10 15]]
[[ 2  7 10 15]
 [ 3 10 14 19]
 [ 6 15 15 19]]


In [20]:
a9 = np.array([3,2,6,4,5])
a10 = np.array([50,30,40,20,10])
a11 = np.array([400,300,600,100,200])
d = np.lexsort((a9,a10,a11)) #np.lexsort()函数只接受一个参数，返回值为按照参数最后一个数据进行排序得到的下标,不会改变原数组顺序

print(d)
print()
print(a9)
print(a10)
print(a11)
print()
print(a9[d])
print(a10[d])
print(a11[d])
print()
#zip () 函数用于将可迭代的对象作为参数，将对象中对应的元素打包成一个个元组(纵向打包，对象元素个数不相同则与最短的对象一致)，然后返回由这些元组组成的 zip 对象。
print(zip(a9[d],a10[d],a11[d]))  #zip()函数返回一个对象
print(list(zip(a9[d],a10[d],a11[d]))) #将zip()返回的对象列表化

[3 4 1 0 2]

[3 2 6 4 5]
[50 30 40 20 10]
[400 300 600 100 200]

[4 5 2 3 6]
[20 10 30 50 40]
[100 200 300 400 600]

[(4, 20, 100), (5, 10, 200), (2, 30, 300), (3, 50, 400), (6, 40, 600)]


In [7]:
a12 = np.array([1,1,1,1,1,2,2,2,2,2,3,3,3])
print(a12)
print(np.unique(a12)) #调用np.unique(arr)去重，但不会影响数组本身
print(a12)
a13 = np.arange(3)
print(a13)
print(np.tile(a13,3)) #调用np.tile(arr,reps)实现数组重复,但不会影响数组本身
print(np.repeat(a13,3)) #调用np.repeat(arr,reps)实现对数组中的每个元素的重复,但不会影响数组本身
print(a13)

[1 1 1 1 1 2 2 2 2 2 3 3 3]
[1 2 3]
[1 1 1 1 1 2 2 2 2 2 3 3 3]
[0 1 2]
[0 1 2 0 1 2 0 1 2]
[0 0 0 1 1 1 2 2 2]
[0 1 2]


In [4]:
a13 = np.arange(1,13).reshape(3,4)
print(a13)
print(np.sum(a13)) #调用np.sum（arr）函数求和该数组
print(a13.sum(1)) #数组的sum(axis)函数，1表示横向求和
print(a13.sum(0)) #0表示纵向求和
print(np.mean(a13)) #调用np.mean(arr)求数组平均值
print(a13.mean(1)) #数组的mean(axis)函数，1表示横向均值
print(a13.mean(0)) #0表示纵向求均值
print(np.std(a13)) #调用np.std（arr）函数求数组标准差
print(np.var(a13)) #调用np.var（arr）函数求数组方差
print(np.max(a13)) #调用np.max（arr）函数求该数组最大值
print(np.argmax(a13)) #调用np.argmax（arr）函数求该数组最大值下标,返回的是一个数
print(np.unravel_index(np.argmax(a13),a13.shape)) #调用np.unravel_index(index,shape)依据下标和维度返回符合数组维度的下标，这里返回最大值的符合数组维度的下标
print(np.min(a13)) #调用np.min（arr）函数求该数组最小值,返回的是一个数
print(np.argmin(a13)) #调用np.argmin（arr）函数求该数组最小值下标
print(np.unravel_index(np.argmin(a13),a13.shape)) #返回最小值的符合数组维度的下标
print(np.cumsum(a13)) #调用np.cumsum(arr)求数组累加和
print(np.cumsum(a13,1)) #调用np.cumsum(arr,axis=1) #求横向累加和
print(np.cumsum(a13,0)) #调用np.cumsum(arr,axis=0) #求纵向累加和
print(np.cumprod(a13)) #调用np.cumprod(arr)求数组累加积
print(np.cumprod(a13,1)) #调用np.cumprod(arr,axis=1) #求横向累加积
print(np.cumprod(a13,0)) #调用np.cumprod(arr,axis=0) #求纵向累加积
print(np.ptp(a13)) #调用np.ptp(arr)求数组极差
print(np.average(a13)) #调用np.average(arr)求数组加权平均值

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
78
[10 26 42]
[15 18 21 24]
6.5
[ 2.5  6.5 10.5]
[5. 6. 7. 8.]
3.452052529534663
11.916666666666666
12
11
(2, 3)
1
0
(0, 0)
[ 1  3  6 10 15 21 28 36 45 55 66 78]
[[ 1  3  6 10]
 [ 5 11 18 26]
 [ 9 19 30 42]]
[[ 1  2  3  4]
 [ 6  8 10 12]
 [15 18 21 24]]
[        1         2         6        24       120       720      5040
     40320    362880   3628800  39916800 479001600]
[[    1     2     6    24]
 [    5    30   210  1680]
 [    9    90   990 11880]]
[[  1   2   3   4]
 [  5  12  21  32]
 [ 45 120 231 384]]
11
6.5


In [26]:
a14 = np.arange(1,10).reshape(3,3)
a15 = np.array([10,10,10])
print(a14)
print()
print(a15)
print()
print(np.add(a14,a15)) #调用np.add(arr1,arr2)实现两个数组相加
print(a14+a15)
print()
print(np.subtract(a14,a15)) #调用np.subtract(arr1,arr2)实现两个数组相减
print(a14-a15)
print()
print(np.multiply(a14,a15)) #调用np.multiply(arr1,arr2)实现两个数组相乘
print(a14*a15)
print()
print(np.divide(a14,a15))  #调用np.divide(arr1,arr2)实现两个数组相除
print(a14/a15)
print()
print(np.square(a15)) #调用np.square(arr),得到数组中每个元素的平方
print()
print(np.sqrt(a15)) #调用np.sqrt(arr),得到数组中每个元素的平方根
print()
print(np.log10(a15)) #调用np.log10(arr)得到每个元素以10为底数的对数

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[10 10 10]

[[11 12 13]
 [14 15 16]
 [17 18 19]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]

[[-9 -8 -7]
 [-6 -5 -4]
 [-3 -2 -1]]
[[-9 -8 -7]
 [-6 -5 -4]
 [-3 -2 -1]]

[[10 20 30]
 [40 50 60]
 [70 80 90]]
[[10 20 30]
 [40 50 60]
 [70 80 90]]

[[0.1 0.2 0.3]
 [0.4 0.5 0.6]
 [0.7 0.8 0.9]]
[[0.1 0.2 0.3]
 [0.4 0.5 0.6]
 [0.7 0.8 0.9]]

[100 100 100]

[3.16227766 3.16227766 3.16227766]

[1. 1. 1.]


In [21]:
a16 = np.array([-1,0.25,10,2.3,2.5,3.6,-1.3])
print(np.reciprocal(a16)) #调用np.reciprocal(arr)求出数组的每个元素的倒数
print(np.abs(a16)) #调用np.abs(arr)求出数组的每个元素的绝对值
print(sorted(a16)) #调用sorted(arr)对数组排序，但不会改变原数组
print(np.median(a16)) #调用np.median(arr)求出数组的中位数
print(np.around(a16)) #调用np.around(arr)求出数组的每个元素的四舍五入后的值
print(np.ceil(a16)) #调用np.ceil(arr)求出数组的每个元素的向上取整后的值
print(np.floor(a16)) #调用np.floor(arr)求出数组的每个元素的向下取整后的值
print(np.modf(a16)) #调用np.modf(arr)将数组的每个元素小数部分和整数部分分开成为两个数组
print(np.sign(a16)) #调用np.sign(arr)求出数组的每个元素的的符号，1正，2零，-1负

[-1.          4.          0.1         0.43478261  0.4         0.27777778
 -0.76923077]
[ 1.    0.25 10.    2.3   2.5   3.6   1.3 ]
[-1.3, -1.0, 0.25, 2.3, 2.5, 3.6, 10.0]
2.3
[-1.  0. 10.  2.  2.  4. -1.]
[-1.  1. 10.  3.  3.  4. -1.]
[-1.  0. 10.  2.  2.  3. -2.]
(array([-0.  ,  0.25,  0.  ,  0.3 ,  0.5 ,  0.6 , -0.3 ]), array([-1.,  0., 10.,  2.,  2.,  3., -1.]))
[-1.  1.  1.  1.  1.  1. -1.]


In [31]:
a17 = np.array([1,2,3])
a18 = np.array([1,2,4])
print(np.power(a17,2)) #调用np.power(arr1,arr2或某个值) 将arr1中的元素为底数，arr2中对应元素或者某个值为幂，计算出结果
print(np.power(a17,a18))
print(np.mod(a17,a18)) #调用np.mod(arr1,arr2或某个值) 将arr1中的元素对arr2中对应元素或者某个值取余，计算出结果
print(np.mod(a17,3))

[1 4 9]
[ 1  4 81]
[0 0 3]
[1 2 0]


In [34]:
a19 = np.array([0,30,45,60,90])
print(np.sin(a19*np.pi/180)) #调用np.sin(arr*np.pi/180)函数求得数组元素的正弦值
print(np.cos(a19*np.pi/180)) #调用np.cos(arr*np.pi/180)函数求得数组元素的余弦值
print(np.tan(a19*np.pi/180)) #调用np.tan(arr*np.pi/180)函数求得数组元素的正切值

[0.         0.5        0.70710678 0.8660254  1.        ]
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]
