# 数组创建

In [5]:
import numpy as np
arr1 = np.array([1,2,3,4])# 采用numpy.array（object）创建一维数组
print("创建的数组为:",arr1)

创建的数组为: [1 2 3 4]


In [8]:
print("arr1数组元素类型:",arr1.dtype)
print("arr1数组维度:",arr1.shape)
print("arr1数组元素个数:",arr1.size)
print("arr1数组内每个元素大小:",arr1.itemsize)

arr1数组元素类型: int32
arr1数组维度: (4,)
arr1数组元素个数: 4
arr1数组内每个元素大小: 4


In [6]:
arr2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [8]:
print("arr2数组维度:",arr2.shape)
arr2.shape = 4,3 #可以更改arr2的维度
print(arr2)

arr2数组维度: (4, 3)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [9]:
arr3 = np.arange(0,1,0.1) # 采用numpy.arange（start=0,stop,step=1,dtype=None）,返回值为数组，不包含终止值
print(arr3)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [10]:
arr3_1 = np.arange(5) #相当于np.arrange(0,5,1)
print(arr3_1)

[0 1 2 3 4]


In [14]:
arr4 = np.linspace(0,100,11,endpoint=False,retstep=True) #采用numpy.linspace（start,stop,num=50,endpoint=True,retstep=False,dtype=None）构造等差数列
print(arr4) #输出会显示间距

(array([ 0.        ,  9.09090909, 18.18181818, 27.27272727, 36.36363636,
       45.45454545, 54.54545455, 63.63636364, 72.72727273, 81.81818182,
       90.90909091]), 9.090909090909092)


In [22]:
arr5 = np.logspace(0,2,20) #numpy.logspace（start,stop,num=50,endpoint=True,base=10.0,dtype=None）构造等比数列,X=10^(start到stop)
print(arr5)

[  1.           1.27427499   1.62377674   2.06913808   2.6366509
   3.35981829   4.2813324    5.45559478   6.95192796   8.8586679
  11.28837892  14.38449888  18.32980711  23.35721469  29.76351442
  37.92690191  48.32930239  61.58482111  78.47599704 100.        ]


In [15]:
arr6=np.zeros((2,3)) #创建指定维度数组，并以0补充,参数为元组
print(arr6)

[[0. 0. 0.]
 [0. 0. 0.]]


In [42]:
arr9 = np.ones((5,3)) #创建元素全为1的数组，参数为元组
print(arr9)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [18]:
arr6_1 = np.zeros(3)
print(arr6_1)

[0. 0. 0.]


In [14]:
arr9_1 = np.ones(5)
print(arr9_1)

[1. 1. 1. 1. 1.]


In [17]:
arr7=np.eye(3) #创建主对角线为1，其他为0的n*n的数组
print(arr7)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [38]:
arr8=np.diag([1,2,3,4]) #创建除对角线其余为0的n*n数组
print(arr8)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


# NumPy类型

In [20]:
print(np.float64(42))

42.0


In [41]:
print(np.int8(42.0))

42


In [19]:
df = np.dtype([("name",np.str_,40),("numitems",np.int64),("price",np.float64)]) #使用numpy.dtype函数得到自定义数组数据类型
print(df)
print(df["name"]) #输出为 顺序+字符编码或类型+大小

[('name', '<U40'), ('numitems', '<i8'), ('price', '<f8')]
<U40


In [30]:
item = np.array([("tomatos",42,4.14),("cabbages",13,1.72)],dtype=df) #使用df自定义数据数据和类型，否则默认数组类型为浮点型
print(item)
print(item[0])
print(item[0][0])
print(item[0]["name"])

[('tomatos', 42, 4.14) ('cabbages', 13, 1.72)]
('tomatos', 42, 4.14)
tomatos
tomatos


# NumPy获取随机数

In [21]:
arr10 = np.random.random(10) #调用numpy.random模块中的random(x)函数生成10个位于[0.0,1.0)的随机数组,x为整数或元组
print(arr10)

[0.60927457 0.0755398  0.05441362 0.07496466 0.59392243 0.10532571
 0.4942526  0.83914151 0.16948686 0.87223135]


In [51]:
arr10_1 = np.random.random((2,2)) #返回2行2列位于[0.0,1.0)的随机二维数组
print(arr10_1)

[[0.00687427 0.76199481]
 [0.73478702 0.06661069]]


In [40]:
arr10_2 = np.random.rand(10) #调用numpy.random模块中的rand(d0,d1....dn)函数生成10个位于[0,1)的随机数,传入数字的个数为维度
print(arr10_2)

[0.70169219 0.2778348  0.82472824 0.97473655 0.17426052 0.38284404
 0.3476404  0.11479885 0.46159736 0.95211826]


In [42]:
arr10_3 = np.random.rand(2,5) #返回2行5列位于[0,1)的随机二维数组
print(arr10_3)

[[0.4917506  0.33252507 0.51218419 0.71531702 0.91183191]
 [0.92231678 0.72239269 0.23255209 0.30525234 0.07008274]]


In [43]:
arr10_4 = np.random.randn(3) #调用np.random模块的randn函数(d0,d1....dn)返回10个符合正态分布的随机数,参数个数表示维度
print(arr10_4)

[ 0.88421886 -1.78317583  0.88701036]


In [44]:
arr10_5 = np.random.randn(2,3) #返回符合正态分布的2行3列二维随机数组
print(arr10_5)

[[ 0.83414622 -1.58018707  0.10735155]
 [-1.27807074  1.61662767 -1.61046125]]


In [45]:
arr10_6=np.random.randint(2,10,5) #调用np.random模块的randint（low,high=None,size=None）函数返回10个位于[2,10)的整数,size可为整数或元组,为None仅返回一个整数
print(arr10_6)

[9 9 2 2 5]


In [47]:
arr10_7=np.random.randint(2,10,(2,5)) #返回位于[2,10)的2行5列的二维整数数组
print(arr10_7)

[[6 2 7 5 2]
 [9 5 8 2 6]]


In [48]:
arr10_8=np.random.randint(2,size=(2,5)) #返回位于[0,2)的2行5列的二维整数数组
print(arr10_8)

[[0 1 0 0 1]
 [1 0 0 0 0]]


In [49]:
arr10_9 = np.random.normal(0,0.1,10) # np.random.normal(loc,scale,size),生成用于正态分布的随机数，loc为期望，scale为标准差，size为数组维数
print(arr10_9)

[ 0.03181897 -0.18416345  0.051958    0.01697182  0.0877833  -0.01514626
  0.11935034  0.11849879  0.05728848 -0.10995221]


In [50]:
arr10_10 = np.random.normal(0,0.1,(2,5)) #返回2行5列均值为0，标准差为0.1的正态分布随机二维数组
print(arr10_10)

[[ 0.00527994  0.20829987  0.09871357  0.03495009  0.04005295]
 [-0.01343154 -0.06297035 -0.12099749 -0.10342378 -0.03218473]]


# 数组索引和切片

In [62]:
n1 = np.array([1,2,3])
print(n1[0])
print(n1[-1])

1
3


In [22]:
n2 = np.array([[1,2,3],[4,5,6]])
print(n2[0][1])
print(n2[0][-1])
print(n2[-1,-1])

2
3
6


切片 start:stop:step , 范围为[start，stop)

In [23]:
n3=np.array([1,2,3,4])
print(n3[0:3:1])
print(n3[0:4:2])
print(n3[0:5]) #step默认为1,相当于[0:4:1]
print(n3[:3]) #start默认为0,step默认为1，相当于[0:3:1]
print(n3[0:]) #stop默认为最后一个元素的下一个下标,相当于[0:4:1]
print(n3[:]) #相当于[0:4]
print(n3[::]) #相当于[0:4:1]
print(n3[::-1]) #step为-1，默认逆序输出
print(n3[:-3:-1]) #step=-1，此时start默认-1，倒数第一个到倒数第三个，不包括倒数第三个
print(n3[-3::-1]) #倒数第三个到倒数最后一个
print(n3[-3:-4:-1]) #倒数第三个到倒数第四个，不包括倒数第四个

[1 2 3]
[1 3]
[1 2 3 4]
[1 2 3]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[4 3 2 1]
[4 3]
[2 1]
[2]


In [24]:
n4=np.array([[1,2,3],[4,5,6]])
print(n4)
print()
print(n4[0:,1:]) # 取第一行第二行，和第二列第三列交叉点的元素
print()
print(n4[0:,1]) # 取第一行第二行，和第二列交叉点的元素
print()
print(n4[((0,1,0),(0,1,2))]) #取n4坐标为[0,0],[1,1],[0,2]的元素

[[1 2 3]
 [4 5 6]]

[[2 3]
 [5 6]]

[2 5]

[1 5 3]


# 数组变换形态

In [120]:
n5=np.arange(10)
print(n5)
n5 = n5.reshape(2,5) #reahpe函数改变数组的维数，这里由一维数组变为2行5列的二维数组
print(n5)
print("转换为2行5列:\n",n5.ravel()) #ravel函数横向展开数组，化成一维
#flatten函数可以横向或纵向展开数组，纵向展开数组参数为'F'.
print("纵向展开后:\n",n5.flatten('F'))
print("横向展开后:\n",n5.flatten())
#使用数组的T属性转置
print("T属性转置后:\n",n5.T)
#使用transpose函数转置
print("transpose函数转置后:\n",n5.transpose())

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
转换为2行5列:
 [0 1 2 3 4 5 6 7 8 9]
纵向展开后:
 [0 5 1 6 2 7 3 8 4 9]
横向展开后:
 [0 1 2 3 4 5 6 7 8 9]
T属性转置后:
 [[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
transpose函数转置后:
 [[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [25]:
n6 = np.arange(12).reshape(3,4)
print(n6)
n7 = n6*3 #n6中的每个元素都*3
print(n7)
print("横向组合为:\n",np.hstack((n6,n7))) #np.hstack((arr1,arr2...))函数横向组合数组
print("纵向组合为:\n",np.vstack((n6,n7,n6))) #np.vstack((arr1,arr2...))函数纵向组合数组
#使用np.concatenate((arr1,arr2...),axis=1或者0)函数组合数组
print("横向组合为:\n",np.concatenate((n6,n7),1)) #横向组合数组
print("纵向组合为:\n",np.concatenate((n6,n7,n6),0)) #纵向组合数组

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]
横向组合为:
 [[ 0  1  2  3  0  3  6  9]
 [ 4  5  6  7 12 15 18 21]
 [ 8  9 10 11 24 27 30 33]]
纵向组合为:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
横向组合为:
 [[ 0  1  2  3  0  3  6  9]
 [ 4  5  6  7 12 15 18 21]
 [ 8  9 10 11 24 27 30 33]]
纵向组合为:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [110]:
n8 = np.arange(16).reshape(4,4)
print(n8)
#采用np.hsplit(arr,num)实现横向分割，num为分割的部份数，分割的部分元素数相同
print("横向分割后:\n",np.hsplit(n8,2)) 
#采用np.vsplit(arr,num)实现纵向分割，num为分割的部份数，分割的部分元素数相同
print("纵向分割后:\n",np.vsplit(n8,2)) 
#使用np.split(arr,num,axis=0或1)实现分割
print("横向分割后:\n",np.split(n8,4,1)) 
print("纵向分割后:\n",np.split(n8,4,0))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
横向分割后:
 [array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]
纵向分割后:
 [array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
横向分割后:
 [array([[ 0],
       [ 4],
       [ 8],
       [12]]), array([[ 1],
       [ 5],
       [ 9],
       [13]]), array([[ 2],
       [ 6],
       [10],
       [14]]), array([[ 3],
       [ 7],
       [11],
       [15]])]
纵向分割后:
 [array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]


# 数组删除和修改

In [121]:
n9=np.arange(6).reshape(3,2)
print(n9)
#采用np.delete(arr,size,axis=0或1)删除某几行或几列，axis=1删除列，axis=0删除行
print("删除第一行:\n",np.delete(n9,0,0))
print("删除第一列:\n",np.delete(n9,0,1))
print("删除第一行和第二行:\n",np.delete(n9,(0,1),0))
n9[0]=[10,20]
print("修改第一行数据:\n",n9)
n9[0][1]=100 #或者n9[0,1]
print("修改第一行第二列的值:\n",n9)

[[0 1]
 [2 3]
 [4 5]]
删除第一行:
 [[2 3]
 [4 5]]
删除第一列:
 [[1]
 [3]
 [5]]
删除第一行和第二行:
 [[4 5]]
修改第一行数据:
 [[10 20]
 [ 2  3]
 [ 4  5]]
修改第一行第二列的值:
 [[ 10 100]
 [  2   3]
 [  4   5]]


## 行操作0 列操作1

# 数组查询

In [124]:
n10=np.arange(10)
print(n10)
#调用np.where(condition,x,y)函数进行查询，如果元素满足条件condition则输出为x,否则y；若果不指定参数x和y，则输出满足函数条件数组元素的下标
print(np.where(n10>5,1,0)) 
print(n10[np.where(n10>5)])

[0 1 2 3 4 5 6 7 8 9]
[0 0 0 0 0 0 1 1 1 1]
[6 7 8 9]
